apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dnorberto
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-deployment
        image: registry.dev.afsmtddso.com/dnorberto-harbor-project/lab-env-repo:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        
